#!/bin/bash
#PBS -A ERDCV00898R40
#PBS -q standard
#PBS -N propLinear
#PBS -l walltime=04:00:00
#PBS -l select=1:ncpus=32:mpiprocs=32
#PBS -M asd@hrwallingford.com
#PBS -m bea
source /opt/modules/default/etc/modules.sh
module unload PrgEnv-pgi
module load  PrgEnv-gnu
module unload cray-libsci
module load acml

cd $PBS_O_WORKDIR
aprun -n 32 parun tank2D_so.py -p -l 2 -O /u/adimako/air-water-vv/inputTemplates/petsc.options.asm -F -D results
